language: php
php:
  - 5.6
  - 7.0

before_script:
  - mkdir -p build/logs
  - composer update --prefer-lowest

script:
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml test/

after_success:
 - php vendor/bin/coveralls -v